META:
  - '/root/autodl-tmp/tvl/Touch-Vision-Language-Dataset/alpaca_gpt4_data.json'
  - '/root/autodl-tmp/tvl/Touch-Vision-Language-Dataset/llava_instruct_150k.json'
  - '/root/autodl-tmp/tvl/Touch-Vision-Language-Dataset/tvl_dataset/ssvtp/finetune.json'
  - '/root/autodl-tmp/tvl/Touch-Vision-Language-Dataset/tvl_dataset/hct/data1/finetune.json'
