META:
- "/root/autodl-tmp/tvl/Touch-Vision-Language-Dataset/cc3m.csv"
- "/root/autodl-tmp/tvl/Touch-Vision-Language-Dataset/tvl_dataset/hct/data1/train.csv"
- "/root/autodl-tmp/tvl/Touch-Vision-Language-Dataset/tvl_dataset/ssvtp/train.csv"